/* Real-browser acceptance checks; run in CI against a temporary synthetic workspace. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {spawn, execFileSync} = require('node:child_process');
const {chromium} = require('playwright');
const AxeBuilder = require('@axe-core/playwright').default;
const python = process.env.TRACEAML_TEST_PYTHON || 'python';
const home = fs.mkdtempSync(path.join(os.tmpdir(), 'traceaml-gui-'));
const directory = path.join(home, 'workspace');
execFileSync(python, ['-m', 'traceaml.cli', 'provision', '--directory', directory, '--demo'], {stdio:['ignore','ignore','inherit']});
const token = fs.readFileSync(path.join(directory, 'secrets/admin.token'),'utf8').trim();
const principalsFile=path.join(directory,'secrets/principals.json');
const principals=JSON.parse(fs.readFileSync(principalsFile,'utf8'));
const viewerToken='v'.repeat(43);
principals.push({...principals[0],subject:'viewer',role:'viewer',token_hash:require('node:crypto').createHash('sha256').update(viewerToken).digest('hex')});
fs.writeFileSync(principalsFile,JSON.stringify(principals),{mode:0o600});
const port=8127,base=`http://127.0.0.1:${port}`;
const server=spawn(python,['-m','traceaml.cli','serve','--config',path.join(directory,'service.json'),'--port',String(port)],{stdio:'ignore'});
let browser;
const errors=[];
async function login(page,value=token){await page.locator('#token').fill(value);await page.locator('#login-submit').click();await page.locator('#case-content').waitFor();}
async function accessible(page,label){const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(result.violations.map(x=>({id:x.id,nodes:x.nodes.map(n=>n.target)})),[],`${label}: accessibility violations`);}
async function main(){
 for(let i=0;i<100;i++){try{if((await fetch(base+'/health/ready')).ok)break;}catch{}if(i===99)throw Error('Service did not start');await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch();
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 const page=await context.newPage();
 page.on('pageerror',error=>errors.push(error.message));
 await page.goto(base);
 await accessible(page,'Sign in');
 await page.locator('#token').fill('invalid');await page.locator('#login-submit').click();await page.locator('#login-error').waitFor();
 await login(page);
 await page.locator('#case-list button').filter({hasText:'Northstar'}).click();
 await page.waitForFunction(()=>document.querySelector('#case-title').textContent.includes('Northstar'));
 assert.equal(await page.locator('#transaction-count').textContent(),'3');
 assert.equal(await page.locator('#synthetic-badge').isVisible(),true);
 await accessible(page,'Case overview');
 fs.mkdirSync('gui-artifacts',{recursive:true});
 await page.screenshot({path:'gui-artifacts/workspace-desktop.png',fullPage:true});
 await page.locator('#tab-evidence').click();
 assert.ok(await page.locator('#evidence-library .finding-card').count()>=3);
 assert.equal(await page.locator('#evidence-library pre').count(),0);
 await accessible(page,'Evidence cards');
 await page.screenshot({path:'gui-artifacts/evidence-desktop.png',fullPage:true});
 await page.locator('#tab-transactions').click();
 await page.getByRole('button',{name:'Inspect TX-78453',exact:true}).click();
 await page.locator('#transaction-dialog').waitFor();
 await accessible(page,'Transaction dialog');
 await page.locator('#review-comment').fill('Source checked; downstream movement needs follow-up.');
 await page.locator('#review-decision').selectOption('escalated');
 await page.locator('#review-submit').click();
 await page.locator('#transaction-dialog').waitFor({state:'hidden'});
 await page.waitForFunction(()=>document.querySelector('#transaction-rows').textContent.includes('Escalated'));
 await page.locator('#tab-activity').click();
 await page.waitForFunction(()=>document.querySelector('#activity-list').textContent.includes('Source checked'));
 await page.locator('#note').fill('<img src=x onerror=alert(1)> A literal note, rendered safely.');
 await page.locator('#add-note').click();
 await page.waitForFunction(()=>document.querySelector('#notes-list').textContent.includes('literal note'));
 assert.equal(await page.locator('#notes-list img').count(),0);
 await page.locator('#case-manage').click();
 await page.locator('#status').selectOption('in_review');
 await page.locator('#assignee').selectOption('demo-admin');
 await page.locator('#save').click();await page.locator('#manage-dialog').waitFor({state:'hidden'});
 await page.waitForFunction(()=>document.querySelector('#case-meta').textContent.includes('In review'));
 await page.locator('#tab-overview').click();
 await page.locator('#pack-select').selectOption('uk');await page.locator('#investigate').click();
 await page.waitForFunction(()=>document.querySelector('#report-pack').textContent==='UK');
 await page.locator('#audit').click();await page.waitForFunction(()=>document.querySelector('#audit-result').textContent.includes('Verified'));
 await page.locator('#tab-evidence').click();
 const downloading=page.waitForEvent('download');await page.locator('#export').click();const download=await downloading;assert.ok(download.suggestedFilename().endsWith('.taenc'));
 await page.locator('#import-open').click();await page.locator('.account-create summary').click();
 await page.locator('#account-id').fill('GUI-NEW');await page.locator('#account-label').fill('Synthetic browser test');await page.locator('#account-currency').fill('EUR');await page.locator('#account-submit').click();
 await page.waitForFunction(()=>document.querySelector('#import-result').textContent.includes('Account created'));
 const transaction={transaction_id:'GUI-TX',occurred_at:'2026-10-01T12:00:00Z',amount:'15000.00',currency:'EUR',originator_account:'GUI-NEW',beneficiary_account:'ACCT-NORTHSTAR-01',originator_country:'DE',beneficiary_country:'GB'};
 await page.locator('#import').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify([transaction,{...transaction,transaction_id:'GUI-BAD',amount:'NaN'}]))});
 await page.locator('#import-submit').click();await page.locator('#import-error').waitFor();
 await page.locator('#import').setInputFiles({name:'transactions.csv',mimeType:'text/csv',buffer:Buffer.from(Object.keys(transaction).join(',')+'\n'+Object.values(transaction).join(','))});
 await page.locator('#import-submit').click();await page.waitForFunction(()=>document.querySelector('#import-result').textContent.includes('1 transactions imported'));
 await page.getByRole('button',{name:'Done',exact:true}).click();
 await page.locator('#create-open').click();await page.locator('#title').fill('Browser acceptance case');await page.locator('#subject-account').fill('GUI-NEW');await page.locator('#create-submit').click();
 await page.locator('#create-dialog').waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelector('#case-title').textContent==='Browser acceptance case');
 await page.locator('#investigate').click();await page.waitForFunction(()=>document.querySelector('#evidence-count').textContent==='2');
 await page.locator('#case-manage').click();await page.locator('#status').selectOption('in_review');await page.locator('#save').click();await page.locator('#manage-dialog').waitFor({state:'hidden'});
 await page.waitForFunction(()=>document.querySelector('#case-meta').textContent.includes('In review'));
 await page.locator('#case-manage').click();await page.locator('#status').selectOption('closed');await page.locator('#disposition').fill('Synthetic acceptance only; source reviewed.');await page.locator('#save').click();await page.locator('#manage-dialog').waitFor({state:'hidden'});
 await page.waitForFunction(()=>document.querySelector('#case-meta').textContent.includes('Closed'));assert.equal(await page.locator('#case-manage').isDisabled(),true);
 assert.ok((await page.locator('#brief-card').textContent()).includes('Synthetic acceptance only'));
 // Keyboard section navigation, native dialog Escape, re-authentication persistence.
 await page.locator('#tab-overview').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#tab-transactions').getAttribute('aria-selected'),'true');
 await page.reload();assert.equal(await page.locator('#login').isVisible(),true);await login(page);
 await page.locator('#case-list button').filter({hasText:'Northstar'}).click();await page.waitForFunction(()=>document.querySelector('#case-title').textContent.includes('Northstar'));
 await page.locator('#tab-transactions').click();await page.getByRole('button',{name:'Inspect TX-78453',exact:true}).click();
 assert.ok((await page.locator('#previous-reviews').textContent()).includes('Source checked'));await page.keyboard.press('Escape');assert.equal(await page.locator('#transaction-dialog').isVisible(),false);
 for(const width of [390,768,1024]){await page.setViewportSize({width,height:900});await page.locator('#tab-overview').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,`Overflow at ${width}`);await accessible(page,`Workspace ${width}px`);}
 await page.setViewportSize({width:390,height:900});await page.screenshot({path:'gui-artifacts/workspace-mobile.png',fullPage:true});
 await page.locator('#logout').click();await login(page,viewerToken);assert.equal(await page.locator('#create-open').isDisabled(),true);assert.equal(await page.locator('#import-open').isDisabled(),true);assert.equal(await page.locator('#case-manage').isDisabled(),true);
 await page.locator('#tab-transactions').click();await page.locator('#transaction-rows button').first().click();assert.equal(await page.locator('#review-submit').isDisabled(),true);
 await accessible(page,'Viewer read-only transaction');
 assert.deepEqual(errors,[],'Browser JavaScript errors');
 console.log('Browser acceptance passed: evidence, transaction reviews, notes, imports, case lifecycle, export, audit, persistence, roles, keyboard, responsive layout, and accessibility.');
}
main().catch(async error=>{console.error(error);if(browser){const page=browser.contexts()[0]?.pages()[0];if(page){fs.mkdirSync('gui-artifacts',{recursive:true});await page.screenshot({path:'gui-artifacts/failure.png',fullPage:true}).catch(()=>{});}}process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.kill();fs.rmSync(home,{recursive:true,force:true});});
